# - name: Download Dotfiles
#   hosts: localmac
#   connection: local
#   vars:
#     branch: master
#   tasks:
#     - name: Git Clone
#       git: repo=git@github.com:i-amd3/dotfiles.git dest={{dotfiles}} version={{branch}}

- name: Setup Dotfiles
  hosts: localmac
  connection: local
  vars:
    vimdir: "{{dotfiles}}/vim"
  tasks:
    - name: Mkdir
      file: path={{item}} state=directory
      with_items:
        - "{{vimdir}}"
        - "{{vimdir}}/autoload"
        - "{{xdg_config_dir}}"
        - "{{fish_dir}}"

    - name: Create symbolic link
      file: src={{item.src}} dest={{item.dest}} state=link
      with_items:
        - { src: "{{dotfiles}}/vim",          dest: "{{xdg_config_dir}}/nvim" }
        - { src: "{{dotfiles}}/vimrc",        dest: "{{xdg_config_dir}}/nvim/init.vim" }
        - { src: "{{dotfiles}}/vim",          dest: "{{ansible_env.HOME}}/.vim" }
        - { src: "{{dotfiles}}/vimrc",        dest: "{{ansible_env.HOME}}/.vimrc" }
        - { src: "{{dotfiles}}/config_fish",  dest: "{{fish_dir}}/config.fish" }

- name: Homebrew
  hosts: localmac
  connection: local
  tasks:
    - name: Add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask

    - name: Update homebrew
      homebrew: update_homebrew=yes

    - name: Upgrade homebrew
      homebrew: upgrade_all=yes

    - name: Install homebrew Packages
      homebrew: name="{{item}}" state=latest
      with_items:
        - ctags
        - fish
        - fzf
        - git
        - git-flow
        - gnu-tar
        - jq
        - macvim
        - neovim/neovim/neovim
        - node
        - pandoc
        - python
        - python3
        - tree
        - wget
        - w3m

    - name: Linkapps homebrew
      command: brew link "{{item}}"
      with_items:
        - python
        - python3

    - name: Install homebrew Cask Packages
      homebrew_cask: name="{{item}}" state=present
      with_items:
        - google-chrome
        - google-japanese-ime
        - iterm2
        - virtualbox
        - vagrant
        - vagrant-manager

    - name: Cleanup homebrew
      command: brew cleanup

    - name: Cleanup homebrew cask
      command: brew cask cleanup

- name: Pip
  hosts: localmac
  connection: local
  tasks:
    - name: install pip
      command: pip install --upgrade pip setuptools neovim cryptography

    - name: install pip3
      command: pip3 install --upgrade pip setuptools neovim cryptography

- name: Vimplug
  hosts: localmac
  connection: local
  tasks:
    - name: install vimplug
      get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest={{dotfiles}}/vim/autoload/plug.vim force=yes

- name: Git
  hosts: localmac
  connection: local
  vars:
    name: i-amd3
    email: d.kupanhy@gmail.com
    editor: vim
  tasks:
    - name: Setting git name
      git_config: name=user.name scope=global value="{{name}}"

    - name: Setting git email
      git_config: name=user.email scope=global value="{{email}}"

    - name: Setting git editor
      git_config: name=core.editor scope=global value="{{editor}}"

- name: set fish as the default shell
  hosts: localmac
  connection: local
  tasks:
    - name: add fish-shell
      command: sudo echo "/usr/local/bin/fish" >> /etc/shells

    - name: change shell
      command: chsh -s /usr/local/bin/fish

